name: foodie
description: Foodgital Customer's App

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  intl_phone_number_input: ^0.7.0+2
  modal_bottom_sheet: ^2.0.0
  cached_network_image: ^3.0.0
  persistent_bottom_nav_bar: ^4.0.2
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  http: ^0.13.3
  google_fonts: ^2.1.0
  json_serializable: ^4.1.0
  # geolocator: ^7.3.0
  # geocoding: ^2.0.0
  permission: ^0.1.7
  get: ^4.3.0
  intl: ^0.17.0
  shared_preferences: ^2.0.6

  # auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons: ^0.9.1

flutter_icons:
  image_path: "assets/images/global/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding/
    - assets/images/
    - assets/icons/
    - assets/svgfiles/
  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/SofiaPro.otf
        - asset: assets/fonts/SofiaProBold.otf
        - asset: assets/fonts/SofiaProBold.otf
